Repository developersociety/django-template, pull requests merged in 2020-08, with the labels that each got.

#208 Fix fab translations
  {{cookiecutter.project_slug}}/fabfile.py
Labels: backend

#210 Leave django admin app enabled - wagtail admin needs it.
  {{cookiecutter.project_slug}}/project/settings/base.py
Labels: backend, tiny

#209 Add mixin for cross-browser word breaking
  {{cookiecutter.project_slug}}/static/src/scss/mixins/_common.scss
Labels: frontend
