Repository developersociety/django-template, pull requests merged in 2021-04, with the labels that each got.

#231 SVG extra bits
  .gitignore
  {{cookiecutter.project_slug}}/.gitignore
  {{cookiecutter.project_slug}}/static/src/scss/forms/_forms.scss
  {{cookiecutter.project_slug}}/static/src/sprite/alert.svg
  {{cookiecutter.project_slug}}/static/src/sprite/arrow_down.svg
  {{cookiecutter.project_slug}}/static/src/sprite/arrow_left.svg
  {{cookiecutter.project_slug}}/static/src/sprite/arrow_right.svg
  {{cookiecutter.project_slug}}/static/src/sprite/arrow_up.svg
  {{cookiecutter.project_slug}}/static/src/sprite/burger.svg
  {{cookiecutter.project_slug}}/static/src/sprite/chevron_down.svg
  {{cookiecutter.project_slug}}/static/src/sprite/chevron_left.svg
  {{cookiecutter.project_slug}}/static/src/sprite/chevron_right.svg
  {{cookiecutter.project_slug}}/static/src/sprite/chevron_up.svg
  {{cookiecutter.project_slug}}/static/src/sprite/close.svg
  {{cookiecutter.project_slug}}/static/src/sprite/delete.svg
  {{cookiecutter.project_slug}}/static/src/sprite/download.svg
  {{cookiecutter.project_slug}}/static/src/sprite/email.svg
  {{cookiecutter.project_slug}}/static/src/sprite/facebook.svg
  {{cookiecutter.project_slug}}/static/src/sprite/instagram.svg
  {{cookiecutter.project_slug}}/static/src/sprite/minus.svg
  {{cookiecutter.project_slug}}/static/src/sprite/plus.svg
  {{cookiecutter.project_slug}}/static/src/sprite/preview.svg
  {{cookiecutter.project_slug}}/static/src/sprite/tick.svg
  {{cookiecutter.project_slug}}/static/src/sprite/twitter.svg
  {{cookiecutter.project_slug}}/templates/base_wagtail.html
  {{cookiecutter.project_slug}}/templates/includes/sprite.html
  {{cookiecutter.project_slug}}/webpack.config.js
Labels: frontend

#230 Fix 404, demo-styles, debug template
  {{cookiecutter.project_slug}}/project/urls.py
Labels: backend, bug, tiny

#235 WAGTAILEMBEDS_RESPONSIVE_HTML in settings.
  {{cookiecutter.project_slug}}/project/settings/base.py
Labels: backend, tiny
