Repository developersociety/django-template, pull requests merged in 2022-02, with the labels that each got.

#254 Switch Wagtail Font Awesome package
  {{cookiecutter.project_slug}}/apps/pages/blocks.py
  {{cookiecutter.project_slug}}/apps/pages/migrations/0001_initial.py
  {{cookiecutter.project_slug}}/apps/pages/wagtail_hooks.py
  {{cookiecutter.project_slug}}/apps/settings/models.py
  {{cookiecutter.project_slug}}/project/settings/base.py
  {{cookiecutter.project_slug}}/requirements/base.txt
Labels: bug, backend

#255 Drop svg4everybody
  {{cookiecutter.project_slug}}/package.json
  {{cookiecutter.project_slug}}/static/src/js/base.js
Labels: frontend

#256 Allow fab get_media to filter on file extension
  {{cookiecutter.project_slug}}/fabfile.py
Labels: backend
